Feature live backend
jodelajo/fndr pull request #16
Opened 2022-03-07 10:34 UTC by jodelajo

## What this PR does:
- Created AuthContext and AgencyContext
- Fetch data from live backend
- Log in on backend
- Implemented JWToken
- Created popup with details agencycard

https://user-images.githubusercontent.com/74967270/157014837-290b56af-1f4d-406d-a2a6-8dbc782c7e05.mov

2022-03-07 17:25 UTC, Reinoptland requested changes
Good: 

- Using context to make data available to child components (nice)
- Cool idea to make a modal (nice touch!)

Can be improved: 

- Authcontext does not work so well when refreshing the page (jwt in localstorage is ignored)
- company_name is forwarded to every component, better make this change once when you request the data
- LIMIT can just be hardcoded at 18, no need to make it a state
- When updating state together (like in authcontext) don't make seperate states, just make an object instead (and use spread when needed to update it) to avoid rerenders
- Pass 1 function to a form that deals with the request that happens when it is submitted, leave all other state to the form (don't lift it to AuthContext for instance)

Try to avoid: 

- Signup form doesn't work - you should always double check your work before a PR (becomes harder the bigger the PR is haha)
- Don't put credentials in source code this can be a disaster
- PR is rather big (makes it hard to review and to make sure everything is high quality)

2022-03-07 17:25 UTC, Reinoptland commented on src/Pages/Home/HomePage.js
> +  const [limit, setLimit] = useState(18);
Why did you add a state for limit?

2022-03-07 17:25 UTC, Reinoptland commented on src/Pages/Home/HomePage.js
>      isLoading: true,
We could probably add `hasMore` to the state and calculate it based on the `meta` we get back in the response (pretty nice)

```
{
    page: 1,
    agencies: [],
    isLoading: true,
    hasMore: true
 }
```

2022-03-07 17:25 UTC, Reinoptland commented on src/Pages/Home/HomePage.js
>          isLoading: false,
You can calculate `hasMore` true or false here: 

`hasMore: response.data._meta.page < response.data._meta.total_pages`

2022-03-07 17:25 UTC, Reinoptland commented on src/Pages/Home/HomePage.js
> +                <AgencyCard agency={agency} />
Nice 👍

2022-03-07 17:25 UTC, Reinoptland commented on src/Pages/Logout/Logout.js
> +export default function Logout() {
Not used - yet?

2022-03-07 17:25 UTC, Reinoptland commented on src/components/AgencyCard/AgencyCard.js
> +      {selectedAgency &&
This works - as long as the selected agency is in the array of agencies which is loaded (which it might not be if you want to make this part of the shareable link)

2022-03-07 17:25 UTC, Reinoptland commented on src/components/AgencyCard/AgencyCard.js
> +        <PopUp selectedAgency={selectedAgency} />
This kind of PopUp can be done with [`React.Portals`](https://blog.bitsrc.io/understanding-react-portals-ab79827732c7)

2022-03-07 17:25 UTC, Reinoptland commented on src/components/LoginForm/LoginForm.js
> +  if (redirect) {
Probably the AuthContext can just redirect us using `useNavigate`?

https://reactrouter.com/docs/en/v6/api#usenavigate

2022-03-07 17:25 UTC, Reinoptland commented on src/components/SignupForm/SignupForm.js
>        <form className="form">
Did you test this form? Does it actually create new admins? 

I think we're missing an onsubmit function here 😅

2022-03-07 17:25 UTC, Reinoptland commented on src/context/AgencyContext.js
> +export default function AgencyContextProvider({ children }) {
Nice - I like this

2022-03-07 17:25 UTC, Reinoptland commented on src/context/AuthContext.js
> +  const [password, setPassword] = useState("v$*UfieAepz7zuYphJ^^");
It's not smart to put credentials like this in open source code. 

I could wipe out the production database with this (possibly) 

So _never_ put _any_ credentials in your source like this.

2022-03-07 17:25 UTC, Reinoptland commented on src/context/AuthContext.js
> +      setUserToken(content);
Consider combining this into 1 state to avoid unnecessary rerenders

2022-03-07 17:25 UTC, Reinoptland commented on src/context/AuthContext.js
> +export default function AuthContextProvider({ children }) {
I am missing what this AuthContext does on startup

I think it should fetch your userdata when the app starts up and maybe check if your token is still valid

2022-03-07 17:25 UTC, Reinoptland commented on src/context/AuthContext.js
> +      localStorage.setItem("token", content.token);
You store the token in localstorage, but you don't get the token from the storage on startup

2022-03-07 17:25 UTC, Reinoptland commented on src/context/AuthContext.js
> +  const data = {
userName, passWord, setUserName, setPassword etc.. belongs in the form

just pass down login(userName, password) instead

2022-03-08 15:24 UTC, jodelajo commented on src/components/AgencyCard/AgencyCard.js
> +      {selectedAgency &&
This part I don't know how to do it correctly. I simplified it, but I don't know how to make sure that the selected agency is loaded. And I don't know where to place the PopUp-component else then in AgencyCard. (maybe in the homepage???)

2022-03-08 15:39 UTC, jodelajo commented
Hi Rein, 
I've made most of changes, except for the react.portal solution for popup, as we discussed to do this later on.
Also, I didn't know how to make sure that 'selected agency' for PopUp is already fetched from backend...

2022-03-11 08:28 UTC, Reinoptland approved these changes
Nice, this is good for the current set of features. 
On to the next ones!

It can be challenging to choose what state to manage where (component, context etc..) 
So if these are the problems we're having it's a good sign!

2022-03-11 08:28 UTC, merged